version: '3'

services:
    php:
        build: ./
        container_name: laravel-php74cli-bullseye
        restart: always
        ports:
            - 8080:80
        links:
            - database
        volumes:
            - ./:/var/www/html
    database:
        image: postgres:15.4-bullseye
        container_name: postgres-bullseye
        restart: always
        environment:
            POSTGRES_USER: pgadmin
            POSTGRES_PASSWORD: pgadmin
            POSTGRES_DB: laravel
    pgadmin:
        image: dpage/pgadmin4:7.6
        container_name: pgadmin
        restart: always
        links:
            - database
        ports:
            - 8081:80
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@mail.loc
            PGADMIN_DEFAULT_PASSWORD: pgadmin
    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: always
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui

