
services:
    php74apache:
        build: ./
        container_name: applic-php74apache-bullseye
        restart: always
        ports:
            - 8080:80
        links:
            - database
        volumes:
            - ./:/var/www/html

