
services:
    mariadb:
        image: mariadb:10.6-focal
        container_name: mariadb-focal
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: application
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: phpmyadmin
    phpmyadmin:
        image: phpmyadmin:5.0-apache
        container_name: phpmyadmin-buster
        restart: always
        links:
            - mariadb
        ports:
            - 8082:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: phpmyadmin
            PMA_PASSWORD: phpmyadmin
