
services:
    php82cli:
        build: ./
        container_name: applic-php82cli-bookworm
        restart: always
        ports:
            - 8080:8000
            - 5173:5173 #package.json "scripts": {"dev": "vite --host"}
        links:
            - database
        volumes:
            - ./:/var/www/html
        tty: true
        # symfony server:start
        # php artisan serve --host php82cli
        # php yii serve php82cli --port=8000
        # php -S php82cli:8000 -t public
    database:
        image: mariadb:11.3.2-jammy
        container_name: mariadb-jammy
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: applic
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: phpmyadmin
    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: phpmyadmin-apache
        restart: always
        links:
            - database
        ports:
            - 8084:80
        environment:
            PMA_HOST: database
            PMA_USER: phpmyadmin
            PMA_PASSWORD: phpmyadmin
    # mailpit:
    #     image: axllent/mailpit
    #     container_name: mailpit
    #     restart: always
    #     ports:
    #         - 1025:1025 # smtp server
    #         - 8025:8025 # web ui
        
