
services:
  nodejs:
    image: "node:20.12-bookworm"
    container_name: app-nodejs-bookworm
    restart: always
    user: "node"
    working_dir: /home/node/app
    # entrypoint: /bin/bash
    environment:
      - NODE_ENV=development
    ports:
      - 8080:3000 #nodejs
      - 5173:5173 #vue
    links:
      - mongo
    volumes:
      - ./:/home/node/app
    tty: true
    # package.json "scripts": {"dev": "vite --host"}
  database:
    image: mongo:6.0.14-jammy
    container_name: mongo-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=applic
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    ports:
      - "8084:8081"
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH=false

