
services:
    eclipsetemurin17jdk:
        build: ./
        container_name: eclipsetemurin-17jdk-jammy
        restart: always
        links:
            - database
        ports:
            - 8080:8080
        volumes:
            - ./:/var/www/html
        tty: true
        # ./mvnw spring-boot:run
    database:
        image: mariadb:11.2-jammy
        container_name: mariadb-jammy
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: spring
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin 
    phpmyadmin:
        image: phpmyadmin:5.2-apache
        container_name: phpmyadmin-buster
        restart: always
        links:
            - database
        ports:
            - 8082:80
        environment:
            PMA_HOST: database
            PMA_USER: admin
            PMA_PASSWORD: admin


